### ISSUE TITLE
Throws TypeError: 'NoneType' object is not iterable on load

### ISSUE THREAD

**Issue by cyian-1756** [wezu/koparka#10]
If I try to load a level the following error is thrown 

```Traceback (most recent call last):
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 52, in eventLoopTask
    self.doEvents()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 46, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 103, in processEvent
    messenger.send(eventName, paramList)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 327, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 412, in __dispatch
    method (*(extraArgs + sentArgs))
  File "main.py", line 1261, in load
    self.current_grass_textures)
  File "/home/wil/code/koparka/sqliteloader.py", line 121, in LoadScene
    row = dict(cur.fetchone())
TypeError: 'NoneType' object is not iterable
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "main.py", line 1817, in <module>
    base.run()
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 2986, in run
    self.taskMgr.run()
  File "/usr/share/panda3d/direct/task/Task.py", line 510, in run
    self.step()
  File "/usr/share/panda3d/direct/task/Task.py", line 467, in step
    self.mgr.poll()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 52, in eventLoopTask
    self.doEvents()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 46, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 103, in processEvent
    messenger.send(eventName, paramList)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 327, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 412, in __dispatch
    method (*(extraArgs + sentArgs))
  File "main.py", line 1261, in load
    self.current_grass_textures)
  File "/home/wil/code/koparka/sqliteloader.py", line 121, in LoadScene
    row = dict(cur.fetchone())
TypeError: 'NoneType' object is not iterable```

running on Ubuntu 16.04 with Python 2.7.12

**Comment by wezu** [comment]
It looks like there's a missing record in the sqlite database (or it's failing to load find it). I'm looking into it, but so far a was not able to reproduce it.
